// filter's action types
export const FILTER_TRANSFER_NONE = 'FILTER_TRANSFER_NONE';
export const FILTER_TRANSFER_ALL = 'FILTER_TRANSFER_ALL';
export const FILTER_TRANSFER_1 = 'FILTER_TRANSFER_1';
export const FILTER_TRANSFER_2 = 'FILTER_TRANSFER_2';
export const FILTER_TRANSFER_3 = 'FILTER_TRANSFER_3';
